# permissions for end users to view availablehosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: availablehost-viewer-role
rules:
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - availablehosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - availablehosts/status
  verbs:
  - get
