# permissions for end users to edit availablehosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: availablehost-editor-role
rules:
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - availablehosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - availablehosts/status
  verbs:
  - get
